sudo: required
services:
  - docker
language: bash

branches:
  only:
    - master

jobs:
  include:
    - stage: Build image
      env: ARCH=x64
      script:
      - ./travis_scripts/build_$ARCH.sh
    - stage: Build image
      env: ARCH=arm
      script:
      - ./travis_scripts/build_$ARCH.sh
    - stage: Trigger builds
      script:
      - ./travis_scripts/trigger_builds.sh